scripts/gcovr
Replace commonprefix() with commonpath() to correctly find common dirs.
Currently commonprefix() returns nonsensical paths (as the documenation
warns). commonpath() instead returns only real directories. This fixes #52
=> Replace commonprefix() with commonpath() to correctly find common dirs

scripts/gcovr
on windows/mingw the -r --root options leads to no coverage info. Therefore a root should not be given.
This leads to an error in output of gcovr (adding str to None)
This file was edited on github online
=> Bugfix for windows usage: required no root option

scripts/gcovr
llvm-cov sometimes outputs that non-code lines are uncovered (and
which lines it reports changes from version to version, and even
from -std=gnu++11 to -std=gnu++14). While llvm-cov should obviously
fix its own bug, this is a far quicker fix.
=> llvm-cov: Check that code exists on lines before marking as uncovered

scripts/gcovr
Previously, `gcovr` would get tangled up if you tried to output to a relative directory, and change the root (`root_dir`) away from the invocation working directory (`starting_dir`)
=> fixed --root option

scripts/gcovr
Fixes an issue with gcovr being run on projects with out-of-source
builds, e.g. CMake-based builds. If --object-directory is given, this
path will be scanned in addition to --root to find gcda/gcno files.
Possible fix for issue #64
=> Use --object-directory to scan for gcov data files

scripts/gcovr
if all files names start with the same string this string
will be removed by commonprefix. Use dirs as input for
commonprefix.
=> fix common prefix detection for files

scripts/gcovr
This option provides ability to set output html files
encoding other than default UTF-8.
Same as #123 but relative to branch master.
=> Adding --html-encoding command line option

.travis.yml
pypy3 is broken on travis-ci c.f. travis-ci/travis-ci#6277
Update `.travis.yml` to use `pypy3.5-5.8.0` for testing
=> Use pypy3.5-5.8.0 for testing

scripts/gcovr
Hello,
I fixed an issue with python3.x that prevented to create html reports due to missing 'iZip' function in itertools. gcovr now uses 'zip' when running with python 3.x directly
=> Python3.x iZip issues fixed

scripts/gcovr
The gcov reports (from which gcovr output is generated) use '/' as the
path separator in filenames, regardless of the path separator used by
the operating system. This breaks attempts to read files located in
subdirectories while generating --html-details reports on Windows.
This commit fixes the issue by replacing '/'s present in the gcov
filename with Python's OS-sensitive os.sep character.
=> Fix gcov '/'s breaking --html-details on Windows

gcovr/tests/bad++char/reference/coverage.xml, gcovr/tests/cmake_oos/reference/coverage.xml, gcovr/tests/dot/reference/coverage.xml, gcovr/tests/excl-branch/reference/coverage.xml, gcovr/tests/excl-line/reference/coverage.xml, gcovr/tests/filter-test/reference/coverage.xml, gcovr/tests/filter-test2/reference/coverage.xml, gcovr/tests/linked/reference/coverage.xml, gcovr/tests/nested/reference/coverage.xml, gcovr/tests/nested2/reference/coverage.xml, gcovr/tests/nested3/reference/coverage.xml, gcovr/tests/oos/reference/coverage.xml, gcovr/tests/oos2/reference/coverage.xml, gcovr/tests/shared_lib/reference/coverage.xml, gcovr/tests/simple1/reference/coverage.xml, gcovr/tests/wspace/reference/coverage.xml, scripts/gcovr
Adding Cobertura's coverage-04.dtd attributes to the coverage-element and adjusting test references.
=> Resolves 164. 

scripts/gcovr
`flake8 scripts/gcovr` returns:
```
scripts/gcovr:35:1: E722 do not use bare except'
scripts/gcovr:45:1: F401 'posixpath' imported but unused
scripts/gcovr:46:1: F401 'itertools' imported but unused
scripts/gcovr:61:20: W291 trailing whitespace
scripts/gcovr:179:17: E265 block comment should start with '# '
scripts/gcovr:308:1: E305 expected 2 blank lines after class or function definition, found 1
scripts/gcovr:362:13: E265 block comment should start with '# '
scripts/gcovr:365:17: E265 block comment should start with '# '
scripts/gcovr:372:13: E265 block comment should start with '# '
scripts/gcovr:373:13: E265 block comment should start with '# '
scripts/gcovr:375:17: E265 block comment should start with '# '
scripts/gcovr:378:21: E265 block comment should start with '# ' …
```
=> Fix most PEP 8 warnings

gcovr/tests/simple1/reference/coverage.xml, gcovr/tests/test_gcovr.py, gcovr/tests/use-existing/reference/coverage.xml
The work on #186 and #164  by @libPhipp highlighted two problems with the XML tests:
1. The XML files are scrubbed with a simple regex to remove the gcovr version. This also removes the XML version, thus creating an invalid XML document. The version regex was made more picky to only scrub gcovr versions.
2. The tests did not assert that exactly the expected document was created, but would ignore unexpected data. Now the documents must be an exact match. Formatting and order is still ignored.
=> Saner XML tests

gcovr/tests/simple1/Makefile, scripts/gcovr
This might be useful to fail tests if coverage is not high enough.
=> Add --fail-under-line and --fail-under-branch options to return exit status 2/4/6 under a coverage threshold

scripts/gcovr
When building exclusion filters from CLI input on Windows, the backslash
path separators from os.path.realpath aren't properly escaped before
being built into a regex.
This refactors the process of building the filter into a function, and
includes alternate logic for constructing the filter on Windows in order
to escape the path separators without escaping the CLI input.
=> Fix exclude filters on Windows

.travis.yml, doc/examples/test_examples.py, doc/include_anchors.py, gcovr/tests/test_gcovr.py, scripts/gcovr, setup.py
Follow-up on #187 
Added TravisCI testing.
`admin` folder is excluded from the check
There are 2 `# noqa` exceptions in `scripts/gcovr`:
```
scripts/gcovr:592:13: E722 do not use bare except'
scripts/gcovr:675:17: E722 do not use bare except'
```
=> Fix most PEP 8 warnings + CI tests

scripts/gcovr
Add validation. Threshold must be in range 0.0-100.0
c.f. https://github.com/gcovr/gcovr/issues/98#issuecomment-356763747
=> Add validation for "--fail-under-line" and "--fail-under-branch" options

README.md
The current README is a bit spartan. This PR adds:
- :link: lots of useful links right at the top
- :framed_picture: screenshots
- :building_construction: installation instructions
- :rocket: quickstart documentation
- :hammer: contributing guidelines
This cannibalizes a bit on the [guide](http://gcovr.com/guide.html), but I'd rather have the important parts right on the repository start page.
A note on the developer role: I've currently set up the pull requests so that they can be merged by any developer if another developer has approved the PR through GitHub's code review features. (And the Travis build must pass, and there mustn't be any merge conflicts). The goal is that every change that is merged into master will have been seen by at least two people. So the developer role is more …
=> expand README with user + contribution guides

setup.cfg
python setup.py bdist_wheel creates a Pure Python Wheel based on running Python version. Add a directive in setup.cfg to build a Universal Wheel that supports both Python 2 and 3.
c.f. https://packaging.python.org/tutorials/distributing-packages/#universal-
wheels
=> Build universal wheel

appveyor.yml, gcovr/tests/cmake_oos/CMakeLists.txt, gcovr/tests/cmake_oos/Makefile, gcovr/tests/filter-test2/Makefile, gcovr/tests/shared_lib/Makefile, gcovr/tests/test_gcovr.py, scripts/gcovr, setup.py
I based this on latk/gcovr@772df7869e723db0a7b35827aea594a9517485b0 as mentioned in #189 
Working through all issues seen by the CI build except for one test which is now skipped when testing under windows: `test_linked (test_gcovr.GcovrHtml)`
Test results can be seen here: https://ci.appveyor.com/project/mayeut/gcovr/build/1.0.35
=> Add AppVeyor CI

AUTHORS.txt, CHANGELOG.txt, LICENSE.txt, README.md
- The changelog lists the most relevant changes since the 3.3 release
- The AUTHORS file now lists *all* contributors, as extracted from the git log.
- The copyright statement in the README and LICENSE now states copyright for the 2013–2018 period, credited collectively to “the gcovr authors”.
This PR is part of the 3.4 release preparations, see #202.
=> Update changelog, copyright, and author list

AUTHORS.txt, gcovr/tests/bad++char/Makefile, gcovr/tests/cmake_oos/Makefile, gcovr/tests/dot/Makefile, gcovr/tests/excl-branch/Makefile, gcovr/tests/excl-line/Makefile, gcovr/tests/filter-test/Makefile, gcovr/tests/filter-test2/Makefile, gcovr/tests/linked/Makefile, gcovr/tests/nested/Makefile, gcovr/tests/nested2-use-existing/Makefile, gcovr/tests/nested2/Makefile, gcovr/tests/nested3/Makefile, gcovr/tests/nobranch/Makefile, gcovr/tests/oos/Makefile, gcovr/tests/oos2/Makefile, gcovr/tests/shared_lib/Makefile, gcovr/tests/simple1/Makefile, gcovr/tests/use-existing/Makefile, gcovr/tests/wspace/Makefile, scripts/gcovr
This fixes #93 with the main fix being a simple change to scripts/gcovr. The other changes were to remove the extra --html flags in the test makefiles to confirm the behaviour of the change.
Eventually, we should have separate tests for html and html-detailed, but that seemed like too big of a change for just this fix.
=> [Fix #93] --html-detailed triggers html reports by itself

scripts/gcovr
Original commit description:
> Refactored main code section into function reducing global variables usage greatly.
Now that we have good tests in place, I'm trying to merge the "dev" branch back into master. Since the branches have diverged considerably, this will happen one commit at a time. This slow approach ensures feature parity.
This commit creates a `main()` function that passes the `options` object to any function that needs it. Previously, `options` (and any other variable from the main code) was a global variable.
Due to indentation changes, the diff on GitHub is of limited use. Consider using a local viewer for a better experience.
The merged commit was originally suggested by @carlos-jenkins in #55. Thank you very much!
=> Merge commit '03ca8da0' from dev

.travis.yml, gcovr/__main__.py, gcovr/tests/bad++char/Makefile, gcovr/tests/cmake_oos/Makefile, gcovr/tests/dot/Makefile, gcovr/tests/excl-branch/Makefile, gcovr/tests/excl-line/Makefile, gcovr/tests/filter-test/Makefile, gcovr/tests/filter-test2/Makefile, gcovr/tests/linked/Makefile, gcovr/tests/nested/Makefile, gcovr/tests/nested2-use-existing/Makefile, gcovr/tests/nested2/Makefile, gcovr/tests/nested3/Makefile, gcovr/tests/nobranch/Makefile, gcovr/tests/oos/Makefile, gcovr/tests/oos2/Makefile, gcovr/tests/shared_lib/Makefile, gcovr/tests/simple1/Makefile, gcovr/tests/test_gcovr.py, gcovr/tests/use-existing/Makefile, gcovr/tests/wspace/Makefile, setup.cfg, setup.py
This allows to run coverage on the module quite easily.
It will also prepare for future re-architecture of gcovr.
=> Move script/gcovr to gcovr/__main__.py

gcovr/__main__.py, gcovr/tests/test_args.py
Test version and help options are printing expected values on stdout.
Test invalid arguments return the correct exit code and print the
correct error message on stderr.
=> Add tests for some command line arguments

gcovr/__main__.py, gcovr/coverage.py, gcovr/gcov.py, gcovr/tests/test_gcov_parser.py, gcovr/utils.py
This PR refactors the `gcovr.gcov` module. There are _a lot_ of changes. In general, I tried to extract smaller, more meaningful functions, and reduce repeated code. Most functions should now fit into one or two screens.
- Finding the source file from a .gcov file is now done by `guess_source_file_name()`, `guess_source_file_name_via_aliases()` and `guess_source_file_name_heuristics()`. The code is now clearer and less deeply nested.
- The actual .gcov file parsing code was gathered into a `GcovParser` class. This class carries the parsing state from one line to the next. Previously, all of these members were variables around a huge loop.
- `parse_all_lines()` runs the parser.
- `parse_line()` parses a single line in a gcov report, and keeps track of relevant state.
- `parse_code_line()` …
=> Refactor gcov parsing code, support upcoming GCC 8 changes

doc/examples/example.sh, doc/examples/example_branches.sh, doc/examples/example_html.sh, doc/examples/example_xml.sh
All other tests use CXX environment variable that defaults to g++.
That allows to set CXX to g++-5 when it's not the default C++ compiler.
Also remove the now unsued scripts folder from PATH
=> Use CXX environment variable in doc/examples tests

gcovr/tests/filter-test2/Makefile, gcovr/tests/shared_lib/Makefile
Add checks for MINGW32_NT to filter-test2 and shared_lib test Makefiles and set BASE_OS to MSYS_NT.
=> Add MINGW32_NT checks for test Makefiles (see #240).

.travis.yml, doc/examples/test_examples.py, gcovr/__main__.py, gcovr/coverage.py, gcovr/gcov.py, gcovr/tests/test_args.py, gcovr/tests/test_gcovr.py, setup.py
Argparse is the better optparse. The only reason why we hadn't already switched was that argparse was only introduced in Python 2.7. Luckily there's a backport that can be installed from PyPI, so I added a version-dependent dependency.
The difficult part was enabling the necessary tests on Travis CI first. This surfaced a few compatibility problems that were accumulated in the recent refactorings. Especially `subprocess` and `runpy` lack many convenience functions, and format strings `"foo{bar}"` must not have empty placeholders `{}`. The tests cannot rely on the `python -m gcovr` style invocation, but the `gcovr` entrypoint script is available anyway. Now all tests except for an XML example pass.
=> Move from optparse to argparse

.travis.yml, doc/examples/test_examples.py
Also remove allowed failure for python 2.6 in travis-ci
=> Mark test_examples xml test as a known failure with python 2.6

AUTHORS.txt, gcovr/gcov.py
=> Add handling of gcov error message "Could not open output file"

.travis.yml
travis-ci PyPI deployment provider now supports skip_existing option.
Fixes #197
=> Enable deployment to Test PyPI

AUTHORS.txt, gcovr/__main__.py
Just a quick fix for:
TypeError: print_summary() takes 1 positional argument but 2 were given
=> Fix --print-summary

.travis.yml, CONTRIBUTING.rst, README.rst, appveyor.yml, doc/source/index.rst, requirements.txt
I dumped my experience from a few PRs into improved contribution docs. My goal is to clarify expectations around PRs, and make it easier to get started in a local development environment. For example, development requirements are now listed in the top-level `requirements.txt`.
This PR also advertises [a Gitter chatroom](https://gitter.im/gcovr/gcovr). Having a chat is desirable because informal real-time discussions are sometimes much more efficient than typing up issue comments. I tested this by walking a first-time contributor through Git and the pull request process.
Gitter is a chat service with good GitHub integration. The chat rooms are fairly open and can be viewed without having to log in. For logged-in users, there is an IRC bridge. Gcovr developers (i.e. anyone with push access …
=> Better contribution docs, mention Gitter chatroom

.travis.yml, doc/examples/test_examples.py, doc/source/guide.rst, gcovr/__main__.py, gcovr/gcov.py, gcovr/tests/test_gcovr.py, setup.py
I've previously advocated for keeping 2.6-compatibility, but have since changed my mind. There are lots of small inconveniences when restricted to the 2.6/3.x common subset. In particular, this drastically restricts the choice of upstream modules.
Old versions of gcovr will of course continue to work. This also means there will never be a gcovr version that works well on Windows with Python 2.6, but since that OS doesn't bundle Python such a
version lock-in is less likely.
Now is a good time to drop support since the next release will likely be 4.0, and we already have a number of other somewhat breaking changes (e.g. different installation procedure). One biggie that is still pending is improved Windows filtering (see #191). I would not like to be locked in to Python 2.6 for the rest of …
=> Drop support for Python 2.6

AUTHORS.txt, gcovr/tests/filter-test2/Makefile, gcovr/tests/shared_lib/Makefile, gcovr/utils.py
When I running gcovr with mingw-w64-x86_64-python3 on mingw64, the `-filter` option is not affect.
It seems mingw-w64-x86_64-python3 use '/' as `os.path.sep` by default, which
diff from other pythons on windows.
Modified tip:
1. Change hard code `"\\"` to `os.path.sep`. It is always safe and does not change the origin behavior.
2. uname on mingw64  env is `MINGW64_NT`,  change the logic to support both.
=> Filter option not affect when running with mingw-w64-x86_64-python3

gcovr/__main__.py, gcovr/gcov.py, gcovr/html_generator.py, gcovr/tests/html-encoding-cp1252/Makefile, gcovr/tests/html-encoding-cp1252/main.cpp, gcovr/tests/html-encoding-cp1252/reference/coverage.main.cpp.html, gcovr/tests/html-encoding-iso-8859-15/Makefile, gcovr/tests/html-encoding-iso-8859-15/main.cpp, gcovr/tests/html-encoding-iso-8859-15/reference/coverage.main.cpp.html, gcovr/tests/source-encoding-cp1252/Makefile, gcovr/tests/source-encoding-cp1252/main.cpp, gcovr/tests/source-encoding-cp1252/reference/coverage.main.cpp.html, gcovr/tests/source-encoding-utf8/Makefile, gcovr/tests/source-encoding-utf8/main.cpp, gcovr/tests/source-encoding-utf8/reference/coverage.main.cpp.html, gcovr/tests/test_gcov_parser.py, gcovr/tests/test_gcovr.py
This PR add `--source-encoding` suggest in #148 .
Note that `io.open` will load file as `unicode` under python2, which may change the coding behavior.
=> Support --source-encoding option.

AUTHORS.txt, CHANGELOG.rst, gcovr/__main__.py, gcovr/html_generator.py, gcovr/tests/html-title-empty/Makefile, gcovr/tests/html-title-empty/main.cpp, gcovr/tests/html-title-empty/reference/coverage.html, gcovr/tests/html-title-empty/reference/coverage.main.cpp.html, gcovr/tests/html-title/Makefile, gcovr/tests/html-title/main.cpp, gcovr/tests/html-title/reference/coverage.html, gcovr/tests/html-title/reference/coverage.main.cpp.html
Split into seperate request like suggested in #262
=> New --html-title option to change the title of the HTML report.

doc/source/cookbook.rst, doc/source/guide.rst, doc/source/index.rst
This adds some basic documentation to clarify how a user can use gcovr with Python C extensions. While not terribly difficult the documentation on the web is extremely sparse in this area and some of the semantics of the python extension build process make things tricky. Most notably the fact `setup.py build_ext` will recompile source code files even if they don't need to be when shared across multiple extension modules. 
Inside the cookbook document there are additional details on how to collect coverage data as well as two code snippets. The first provides and example of a route to build your modules in a fashion that permits code coverage data generation and the second is a python script that can be used to collect the code coverage data into the standard HTML reporting format. The …
=> Python c extension documentation

.travis.yml, appveyor.yml, gcovr/__main__.py, gcovr/configuration.py
Extracts the command line api configuration out into a separate module (configuration.py). The `GcovrConfigOption` classes store all of the necessary information to add themselves to an argparse parser and make that information easily accessible for any future configuration schemes. (The objects produced by `add_argument` are rather opaque.) 
Todo:
This is a building block for eventually addressing #229
=> Move argument validation outside of argparse

AUTHORS.txt, gcovr/tests/linked/Makefile, gcovr/utils.py
The directory tree being scanned may in fact be a directed graph, with
cycles, due to following symbolic links. The kernel imposes a limit on
the number of symbolic links followed in a path, beyond which operations
fail with ELOOP. (According to path_resolution(7), the limit is 40 links
on current Linux.) If the graph is very branchy, it may take a very long
time to fail.
For a real-world example, the Meson build system uses gcovr to provide a
'ninja coverage-xml' target. The systemd project (which uses Meson) has
a test suite which generates a fake sysfs tree, with many circular
references, including 64 self-referential ttyX directories:
$ ls -l build/test/sys/devices/virtual/tty/tty1/subsystem/tty1
lrwxrwxrwx 1 wjt wjt 30 Oct  9 12:16 …
=> search_file: don't visit the same directory more than once

AUTHORS.txt, gcovr/gcov.py, gcovr/tests/test_gcov_parser.py
Hi,
When working with GCC 8 (ref #228) I found a bug whereby if the gcov file is arranged thus:
```
------------------
Foo<int>::Foo():
function Foo<int>::Foo() called 1 returned 100% blocks executed 100%
1:    7:  Foo(): b (1000) {}
------------------
Foo<char>::Foo():
function Foo<char>::Foo() called 0 returned 0% blocks executed 0%
#####:    7:  Foo(): b (1000) {}
------------------
```
instead of:
```
------------------
Foo<char>::Foo():
function Foo<char>::Foo() called 0 returned 0% blocks executed 0%
#####:    7:  Foo(): b (1000) {}
------------------
Foo<int>::Foo():
function Foo<int>::Foo() called 1 returned 100% blocks executed 100%
1:    7:  Foo(): b (1000) {}
------------------
```
then the line in question is flagged as un-hit, because the un-hit indicator `####` occurs after …
=> Fixed issue under gcov 8 where an un-hit section could overwrite a hit in templated code

AUTHORS.txt, doc/source/guide.rst, gcovr/__main__.py, gcovr/configuration.py, gcovr/json_generator.py, gcovr/tests/add_coverages/Makefile
In this PR I try to:
- solve problem with generating output report when '--output' option is missing for json_generator
- add feature suggested in issue #338 about adding wildcards to '--add-tracefile' option
I need a review for the second feature, because I am not sure whether is correctly implemented or should be done totally different.
=> Extensions and fixes for json_generator

README.rst, gcovr/__main__.py, gcovr/configuration.py, gcovr/csv_generator.py, gcovr/tests/csv/Makefile, gcovr/tests/csv/coverage.csv, gcovr/tests/csv/main.cpp, gcovr/tests/csv/reference/coverage.csv, gcovr/tests/test_gcovr.py
This adds a summarized CSV output format.
It includes only the totals/covered/percent per file, without details on the covered lines/branches.
=> Add --csv output

Makefile
To get the full assertion text or run a specific test you have to set TEST_OPTS. This is not possible if test run inside the docker container.
The option is set as environment variable which is used by the make inside docker.
=> Set make variable TEST_OPTS as environment variable inside docker.

gcovr/tests/exclude-relative/Makefile, gcovr/utils.py
If HOME directory is case insensitive the pattern match is also done case insensitive.
Test for exclude filter adapted to give filename with wrong case if testcase.exe exists in filesystem.
=> Compare paths case insensitive #329

.travis.yml, CHANGELOG.rst, appveyor.yml, gcovr/tests/.gitignore, gcovr/tests/add_coverages/.gitignore, gcovr/tests/conftest.py, gcovr/tests/filter-relative-lib/project/.gitignore, gcovr/tests/linked/.gitignore, gcovr/tests/shared_lib/testApp/.gitignore, gcovr/tests/test_gcovr.py
- Extend test option --update_reference for all formats.
- New option --archive_differences to save the different fileas as ZIP. Use this ZIP as artifact in AppVeyor.
The first commit is with a difference to test it in the CI.
=> Extend test framework for CI

CHANGELOG.rst, doc/source/guide.rst, gcovr/configuration.py, gcovr/tests/add_coverages/Makefile, gcovr/tests/exclude-lines-by-pattern/Makefile, gcovr/utils.py
Update documentation for relative filters in configuration files.
Extend the help output for the filter section with directory used for relative filters.
Closes #319.
=> Extend documentation for relative filters

README.rst
=> Fix target for Github build status badge

.github/workflows/test.yml
Additional informations https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/.
=> Fix deprecated set-env

gcovr/gcov.py
When running gcovr with filters, a warning about an unclosed file was
reported for filtered or excluded file. By wrapping the io.read result
in a with statement, proper closure of the file is ensured regardless of
the path taken through the routine.
Test-information:
Checked that gcovr runs that use the -e or -f flags no longer output a
lot of warnings.
=> Always properly close INPUT in process_gcov_data

gcovr/__main__.py
Fix warning from test.
```shell
/usr/bin/python3 -m gcovr -d --json main.json
(WARNING) --output=None option was provided but not used.
```
=> Fix warning in console if not -o is used.

gcovr/tests/.gitattributes
Because of adding references for the different compiler versions  the pattern must be changed. at the moment gcovr language is detected as html because of the refernce data.
=> Fix GitHub language statistics

AUTHORS.txt, CHANGELOG.rst, gcovr/__main__.py
If the root folder occurs somewhere in the file name, it is replaced by the empty string by `root_filter.sub('', filename)`, resulting in an invalid file name. Consider for example the transformation
```
/src/libs/libjhtml/src/libjhtml/DataUri.cc -> libs/libjhtmllibjhtml/DataUri.cc
```
when `--root /src` is given.
This PR fixes the problem by only substituting the root folder at the start of the file name.
=> Fix overzealous substitution of root folder

LICENSE.txt, README.rst, admin/add_copyright.py, doc/examples/test_examples.py, doc/source/conf.py, gcovr/__init__.py, gcovr/__main__.py, gcovr/cobertura_xml_generator.py, gcovr/configuration.py, gcovr/coverage.py, gcovr/coveralls_generator.py, gcovr/csv_generator.py, gcovr/gcov.py, gcovr/html_generator.py, gcovr/json_generator.py, gcovr/sonarqube_generator.py, gcovr/summary_generator.py, gcovr/tests/conftest.py, gcovr/tests/test_args.py, gcovr/tests/test_config.py, gcovr/tests/test_gcov_parser.py, gcovr/tests/test_gcovr.py, gcovr/tests/test_html_generator.py, gcovr/txt_generator.py, gcovr/utils.py, gcovr/version.py, gcovr/workers.py, setup.py
Inspired from another project I added a script which writes the copyright info to each python file. The comment contains the contributors sorted by the contribution date and afterwards by name.
The version in the copiright is used from `__Version__.py`.  For the copyright in the documtation the current year is used instead of the fixed 2018.
One idea is to create also the author list from the git log or to extend the copyright comment to other file types.
=> Add script for copyright header.

.github/workflows/deploy.yml, .github/workflows/test.yml, CHANGELOG.rst, CONTRIBUTING.rst, admin/release_checklist
Test was mentioned in #424. The check can be deactivated by adding the text "[no changelog]" to a single line in the comment.
=> Check if issue is mentioned in changelog.

.github/workflows/test.yml
Fix #457 on master branch.
Without a PR the changelog check is skipped and the dependent checks aren't executed.
[no changelog]
=> Fix check on master (no PR context)

CHANGELOG.rst, Makefile, admin/Dockerfile.qa, gcovr/tests/test_args.py
Extend test with read only output directory.
=> Run as limited user inside docker

setup.py
Given recent refactoring done in #443, use `setuptools.find_packages()` to generate the list of packages for installation.
Fixes #464
[no changelog]
=> Use setuptools.find_packages() in setup.py (fixes #464)

CHANGELOG.rst, doc/source/installation.rst, setup.py
Since 3.5 is EOL, we can drop support.
While updating the docs I noticed that some statements about our test configurations were a bit out of date, so I fixed them as well.
Changelog was updated but doesn't need an issue reference:
[no changelog]
=> Drop support for Python 3.5

.github/workflows/test.yml
This PR contains two changes.
First, the **milestone check** only makes sense on pull requests, so it's now limited to events of that type. Previously, this would cause the CI to fail on the master branch.
Second, running the CI is also useful on **branches other than master**. In particular, this lets contributors run CI on their forked repositories.
Since this is a purely internal change relating to #460:
[no changelog]
=> Make CI run successfully on all branches

doc/requirements.txt
Because of https://github.com/sphinx-contrib/autoprogram/issues/42 version is pinned for Python 3.6.
[no changelog]
=> Fix documentation generation for Python 3.6.

gcovr/writer/html.py
Result from investigation of #345.
[no changelog]
=> Add warning if coverage data has more lines than source files.

admin/Dockerfile.qa
The Docker tests recently started failing with the following message:
> RuntimeError: Click will abort further execution because Python was configured to use ASCII as encoding for the environment. Consult https://click.palletsprojects.com/unicode-support/ for mitigation steps.
>
> This system supports the C.UTF-8 locale which is recommended. You might be able to resolve your issue by exporting the following environment variables:
>
>     export LC_ALL=C.UTF-8
>     export LANG=C.UTF-8
It seems this is related to the recent update of the Click library to version 8. This library is used by tools such as the `black` formatter.
As a fix, these environment variables are set in the Docker container. This should not affect tests on the host systems, since the hosts usually already have a Unicode …
=> fix Docker-based tests by setting Unicode locale

.github/workflows/deploy.yml, .github/workflows/test.yml, admin/release_checklist, gcovr/tests/cmake_oos/CMakeLists.txt, gcovr/tests/cmake_oos_ninja/CMakeLists.txt, requirements.txt, setup.cfg
- Fix problems mentioned in https://github.com/gcovr/gcovr/issues/424#issuecomment-858091994.
- Fix CMake varning because minimum required version was 2.6.4.
The deploy workflow is also executed on `push` and `pull_request` but the publish is skipped. There is also the dist folder saved as artifact.
Now we can be sure that the build will succeed.
[no changelog]
=> Fix deploy workflow.

.github/workflows/deploy.yml, .gitignore, CHANGELOG.rst, requirements.txt, setup.cfg, setup.py
- Fix README.rst for PyPI upload.
- Rename license_file to license_files because of deprecation warning.
- Add twine to the requirements.txt to run check mentioned in https://packaging.python.org/guides/making-a-pypi-friendly-readme/. Our problems are not found by the check.
- Remove the deployment trigger for the release because we want to use annotated tags. The workflow is triggered if a tag is pushed.
=> Fix problems from deployment of release 5.0

CHANGELOG.rst, gcovr/gcov.py, gcovr/tests/cmake_oos/Makefile, gcovr/tests/filter-absolute-from-unfiltered-tracefile/Makefile, gcovr/tests/filter-absolute/Makefile, gcovr/tests/filter-relative-lib-from-unfiltered-tracefile/Makefile, gcovr/tests/filter-relative-lib/Makefile, gcovr/tests/linked/Makefile, gcovr/tests/shared_lib/Makefile, gcovr/tests/simple1/Makefile, gcovr/tests/test_gcovr.py, gcovr/utils.py, gcovr/writer/html.py
Under Windows we have to use junctions instead of symlinks. As I know a Shell can't `cd` into a symbolic link.
With Junctions and a custom `gcov_realpath` for python < 3.8 the tests are now working also on windows.
With this change #535 should change the `gcov_realpath` to not resolve the path to a different drive on windows.
=> Activate symlink tests under Windows

.github/workflows/deploy.yml, .github/workflows/test.yml, CHANGELOG.rst, admin/release_checklist, doc/examples/example_html.sh, doc/examples/example_timestamps.sh, doc/examples/test_examples.py, doc/source/guide-timestamps.rst, doc/source/guide.rst, gcovr/configuration.py, gcovr/tests/test_args.py, gcovr/timestamps.py, gcovr/writer/cobertura.py, gcovr/writer/coveralls.py, gcovr/writer/html.py, noxfile.py
Certain report formats include a timestamp (HTML, Coveralls, Cobertura). It may however be desirable to attribute the report to a different time:
* e.g. date of a commit instead of time when gcovr was run
* CI server might be running with wrong timezone
* the gcovr test suite
Currently, the gcovr test suite scrubs timestamps from the generated files in order to enable comparison. In the future, this option could be used instead. The HTML-example test was already modified to use fixed timestamps in order to avoid unnecessary Git diffs (the html-details example outputs are committed).
The supported date formats for the --timestamp option are the Unix epoch and formats that are like RFC-3339 ("ISO dates" without the more insane features). Time zones are optional.
This should be able to …
=> Add --timestamp option for reproducible reports.

.editorconfig, CHANGELOG.rst
With #538 git was configured to use LF for shell sc ripts. This PR extends the .editorconfig to also use LF.
=> Use LF for sh files.

AUTHORS.txt, CHANGELOG.rst, doc/source/faq.rst, gcovr/configuration.py, gcovr/gcov.py
Using tho option ` --long-file-names` with `llvm-cov` leads to file name larger than 255 characters on our setup and makes `gcovr` unusable. Hence this PR adding an option to disable it.
=> Add an option to disable long file names

.github/workflows/test.yml, CHANGELOG.rst, admin/Dockerfile.qa, doc/requirements.txt, doc/source/installation.rst, setup.py
Python 3.6 was EOL'ed on 23 Dec 2021. In line with gcovr's support policy for Python versions, this pull request removes support for Python 3.6.
References: [PEP 494 (Python 3.6 Release Schedule)](https://www.python.org/dev/peps/pep-0494/), [endoflife.date/python](https://endoflife.date/python)
This has no strong immediate benefits, but will allow us to use more modern Python features in the future. Highlight features of Python 3.7 include:
* [`dataclasses`](https://docs.python.org/3/library/dataclasses.html) to easily define struct-like classes. Could simplify a lot of places where we currently pass around tuples!
* `from __future__ import annotations` for easier type annotations
* guaranteed dict insertion order preservation
* significant improvements to asyncio. Could allow us to …
=> Drop support for Python 3.6

noxfile.py
The venv is reused if the session OR the global setting is True. Therefore if it is activated at global level it can't be turned off local. As a result we have to set it for each session separate.
This was found while testing the session `build_wheel`, the check always used the first installed wheel.
[no changelog]
=> Do not reuse virtual environment.

CHANGELOG.rst, gcovr/configuration.py
The option type wasn't detected correct and the working directory was used instead of the directory of the configuration file.
Closes #567
=> Fix resolution of relative filters in configuration files.

gcovr/tests/test_gcovr.py
This fix a regression problem of #556.
If the data for gcc-5 was used as reference this data was unlinked if --update_reference was used.
[no changelog]
=> Fix update of reference data.

CHANGELOG.rst, admin/add_copyright.py, gcovr/__main__.py, gcovr/tests/test_gcovr.py, gcovr/tests/test_html_generator.py, noxfile.py
As discussed in #540 this PR adds `flake8-print` to check for wrong usage of print instead of the logger.
Following parts must go to STDOUT and use `sys.stdout.write` as in summary report:
- Output of `--version`.
- START/END marker of output in tests.
=> Add flake8-print to check usage of print function.

.gitignore, admin/Dockerfile.qa
As mentioned in #559 the cache isn't used inside docker because it's not persistent.
This PR configures the while cache of the container to be inside the venv folder of the container. Now the PIP and other caches are persistent for different runs of a container instance.
[no changelog]
=> Add persisten cache in docker

CHANGELOG.rst, gcovr/gcov.py, gcovr/tests/threaded/Makefile, noxfile.py, setup.cfg
Activate verbose mode hanging pypy in GitHub actions
=> Workaround for hanging test "threaded" in pypy.

gcovr/tests/test_gcovr.py
Sometimes in the CI C: is detected as free drive on Windows. As a workaround the last free drive shall be used.
[no changelog]
=> Use last free drive because sometimes C: is used.

AUTHORS.txt, CHANGELOG.rst, gcovr/writer/html.py
Hi gcovr team !
The latest version `jinja2==3.1.0` breaks `gcovr==5.0`: `gcovr` tries to import `Markup` from `jinja2`, but it's not available anymore.
This is documented in `jinja2` change note: https://jinja.palletsprojects.com/en/3.1.x/changes/#version-3-1-0
This is my first contribution, and I drafted this PR quite quickly as I suppose many people will soon be impacted. Please tell me if I forgot something important :)
```sh
ptyhon3 -m venv env
source env/bin/activate
pip install gcovr==5.0 jinja2==3.1.0
bash run.sh
```
with the following files
```cc
// main.cc
int main()
{
int a = 1;
return a;
}
```
```sh
gcc --coverage -g -O0 main.cc -o out
./out
gcovr -r . --html --html-details -o cov.html
```
I get the output
```py
Traceback (most recent call last):
File …
```
=> directly import Markup from markupsafe (fix breakage with jinja2>=3.1)

CHANGELOG.rst, gcovr/gcov.py
The directory lock is only for running gcov but not for parsing the data. The next run can override the data and than "FileNotFoundError" (#587) and "KeyError: 'Source'" (#588) occur.
Closes #587 
Closes #588
=> Fix parallel processing of gcov data.

CHANGELOG.rst, admin/bump_version.py, noxfile.py
The option was removed by accident when reformatting all files and apply check to all files. Session isn't failing on error.
=> Fix black check: Option --check needed.

CHANGELOG.rst, gcovr/gcov_parser.py
The check is tested with doctest and prints the gcov data on failure.
=> Add check for required metadata.

CHANGELOG.rst, CONTRIBUTING.rst, noxfile.py
If no argument is given all files are reformatted instead of checked. See also #594.
=> Change black session to reformat files

CHANGELOG.rst, gcovr/gcov.py, gcovr/gcov_parser.py
Gcc-11 has metadata lines without values in the gcov file (see #596). This PR add support for this lines and uses as value `None`.
Closes #596.
=> Fix parsing of gcov metadata

CHANGELOG.rst, gcovr/__main__.py, gcovr/coverage.py, gcovr/decision_analysis.py, gcovr/gcov.py, gcovr/gcov_parser.py, gcovr/merging.py, gcovr/tests/test_gcov_parser.py, gcovr/utils.py, gcovr/writer/cobertura.py, gcovr/writer/coveralls.py, gcovr/writer/csv.py, gcovr/writer/html.py, gcovr/writer/json.py, gcovr/writer/sonarqube.py, gcovr/writer/summary.py, gcovr/writer/txt.py
As a “dividend” from dropping support for Python 3.6, various improvements have become possible. This PR focuses on adding more type annotations for the `gcovr.coverage` data model, externalizing the merging logic, and replacing the increasingly large tuples from `get_global_stats()` and so on with more useful classes. In doing so, a number of bugs were found, but not necessarily fixed as part of this PR.
For reviewing this PR, moving one commit at a time is recommended. The commit messages provide further explanation. Here, I summarize the central changes and consequences.
Python doesn't handle cyclic dependencies very well. Since the coverage data model now provides types that are used in type annotations throughout the code, the `gcovr.coverage` module now cannot have dependencies on …
=> Type checking + refactoring for the coverage data model

noxfile.py
In #597 for gcc-9 Ubuntu 20.04 was used but for gcc-8 the newer 22.04.
In 22.04 the gcc-8 isn't available anymore.
[no changelog]
=> Use ubuntu-20.04 for gcc-8 in docker.

CHANGELOG.rst, admin/Dockerfile.qa, noxfile.py
Recreating the virtual environment and installing the requirements needs some time. If the session `docker_qa_compiler(all)` to update the test data this takes a long time even if the requirements aren't changed.
The sessions for docker don't use python and a virtual environment, therefore the options `--reuse-existing-virtualenvs` and `--no-install` are useless and this PR forwards this options to the `nox` call inside docker.
Here are my measurements for the call `python3 -m nox -s 'docker_qa_compiler(gcc-5) ...`:
- `... -- -k nested`: `0,28s user 0,22s system 0% cpu 2:45,78 total`
- `... --reuse-existing-virtualenvs -- -k nested`: `0,33s user 0,23s system 1% cpu 36,365 total` --> ~ 5 times faster
- `... --reuse-existing-virtualenvs --no-install -- -k nested`: `0,33s user 0,23s system …
=> Forward nox options to call inside docker.

CHANGELOG.rst, gcovr/gcov_parser.py
Fix parser error:
```
(WARNING) Exception during parsing:
UnknownLineType: function prop8_view_postfilter called 8092 returned NAN % blocks executed 19%
```
Closes #627
=> Accept `NAN %` which is used in GCOV 7.5.0 instead of an invalid value.

CHANGELOG.rst, doc/source/guide/merging.rst, gcovr/configuration.py, gcovr/tests/simple1/Makefile, gcovr/tests/simple1/reference/clang-10/coverage.json, gcovr/tests/simple1/reference/clang-10/summary_coverage.json, gcovr/tests/simple1/reference/clang-13/coverage.json, gcovr/tests/simple1/reference/gcc-5/coverage.json, gcovr/tests/simple1/reference/gcc-5/summary_coverage.json, gcovr/tests/simple1/reference/gcc-8/coverage.json, gcovr/tests/simple1/reference/gcc-8/summary_coverage.json, gcovr/tests/test_gcovr.py, gcovr/utils.py, gcovr/writer/cobertura.py, gcovr/writer/html.py, gcovr/writer/json.py, gcovr/writer/txt.py
As suggested in #397 an option `--json-base` is added which is prepended to the file names in the JSON reports. The value is normalized first and `\`are replaced by `/`.
Closes #397
=> Add base path for json.

AUTHORS.txt, doc/source/guide/filters.rst
As discussed in https://github.com/gcovr/gcovr/issues/658 I have added a few examples to the Using filters section and linked the config file explanation, as it contains examples for filters as well.
[no changelog]
=> Add example section for filters

AUTHORS.txt, CHANGELOG.rst, gcovr/tests/linked/reference/clang-10/coverage.html, gcovr/tests/linked/reference/gcc-5/coverage.html, gcovr/tests/linked/reference/gcc-8/coverage.html, gcovr/utils.py, gcovr/writer/html.py
This change fixes the sorting of html reports, for when there are symlinks within the nested directory structure. The sorting of filename will consider the absolute paths, which is already what it renders in the report with.
Note, since we only do the relative-path trick for the html report, we only make this sort-fix for the html report. The other reports are still showing the alternate path, as seen in the linked-txt test report.
Closes #684
=> Issue 684: Fix sorting of html reports when there are symlinks.

.github/workflows/deploy.yml, .github/workflows/test.yml, CHANGELOG.rst, CONTRIBUTING.rst, doc/source/installation.rst, gcovr/tests/test_gcovr.py, noxfile.py
This PR selects the latest GCC version on the system for the tests. If only `gcc` is available the version is detected from the output of `gcc --version`.
If using `qa_compiler` session the default is switched from `gcc-5` to `gcc-11` (the current latest version for the reference data).
=> Detect compiler version from gcc output if not specified.

CHANGELOG.rst, gcovr/__main__.py
If a gcovr.cfg is in the project directory and you run `gcovr --version` the configuration file is read first. This can result in an error.
Closes #695
=> Handle option `--version` before parsing config file.

.github/workflows/deploy.yml, .github/workflows/test.yml, CHANGELOG.rst
In the CI there is the following warning:
```
Node.js 12 actions are deprecated. For more information see:
https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/.
Please update the following actions to use Node.js 16: seanmiddleditch/gha-setup-ninja@master
```
There is now response for https://github.com/seanmiddleditch/gha-setup-ninja/pull/15 since nearly two months. To get rid of the warning we install it now with the package manager.
=> Install ninja in CI with package manager

CHANGELOG.rst, gcovr/gcov_parser.py
Since the patch discussed in #677 is merged to latest `gcc` thwe output is not recognized by `gcovr` anymore (#710).
This PR allows the annotations also for not executed branches and a doctest is added for this new case.
Closes #710
=> Allow annotations for not executed branches.

.github/workflows/test.yml, CHANGELOG.rst
Add python 3.11 to our test matrix and update the special test combinations which use 3.10 to 3.11.
=> Add python 3.11 to test matrix

CHANGELOG.rst, gcovr/workers.py
If `gcovr` is lcalled with `--jobs` and the `gcov` command fails we stay stuck. I reproduced this by adding a unknown option to the `gcov` execution.
As mentioned in https://github.com/gcovr/gcovr/issues/673#issuecomment-1255427992 the problem was the directory lock. This PR catches the exception which can occur in the yield, unlocks the directory and reraise the exception. 
Closes #673
=> Fix deadlog on gcov error

gcovr/workers.py
In https://github.com/gcovr/gcovr/pull/719#discussion_r1112973194 a easier way for the exception handling is defined. This PR changes the handling to use a  `finally` block.
[no changelog]
=> Rework exception handling as described in #719

CHANGELOG.rst, gcovr/decision_analysis.py, gcovr/tests/decisions/main.cpp, gcovr/tests/decisions/reference/clang-10/coverage.functions.html, gcovr/tests/decisions/reference/clang-10/coverage.html, gcovr/tests/decisions/reference/clang-10/coverage.json, gcovr/tests/decisions/reference/clang-10/coverage.main.cpp.118fcbaaba162ba17933c7893247df3a.html, gcovr/tests/decisions/reference/clang-13/coverage.functions.html, gcovr/tests/decisions/reference/clang-13/coverage.json, gcovr/tests/decisions/reference/clang-13/coverage.main.cpp.118fcbaaba162ba17933c7893247df3a.html, gcovr/tests/decisions/reference/gcc-11/coverage.functions.html, gcovr/tests/decisions/reference/gcc-11/coverage.html, gcovr/tests/decisions/reference/gcc-11/coverage.json, gcovr/tests/decisions/reference/gcc-11/coverage.main.cpp.118fcbaaba162ba17933c7893247df3a.html, gcovr/tests/decisions/reference/gcc-5/coverage.functions.html, gcovr/tests/decisions/reference/gcc-5/coverage.html, gcovr/tests/decisions/reference/gcc-5/coverage.json, gcovr/tests/decisions/reference/gcc-5/coverage.main.cpp.118fcbaaba162ba17933c7893247df3a.html, gcovr/tests/decisions/reference/gcc-8/coverage.functions.html, gcovr/tests/decisions/reference/gcc-8/coverage.html, gcovr/tests/decisions/reference/gcc-8/coverage.json, gcovr/tests/decisions/reference/gcc-8/coverage.main.cpp.118fcbaaba162ba17933c7893247df3a.html
Only single line cases are detected by the current decision parser.  This PR extends the decision parser to detect also multi line case statements as suggested in https://github.com/gcovr/gcovr/issues/665#issuecomment-1232581248.
Closes #665
=> Fix problem in decision parser if case is not on a single line with the break statement.

.github/workflows/deploy.yml, noxfile.py, setup.py
When moving the templates the writer the paths were not updated in `setup.py`. This PR updates the paths and extends the session `check_wheel` to create a empty report for each output format. Without the adaption of the paths the check is failing for HTML format.
[no changelog]
=> Fix packaging of templates

.github/workflows/test.yml, noxfile.py
The `qa` session in the docker container for `gcc-5` and `gcc-6` wasn't working anymore. Therefore switch back to the python script.
[no changelog]
=> Use the rst2html.py again to be able to run the doc for all compilers.

CHANGELOG.rst, gcovr/__main__.py, gcovr/configuration.py, gcovr/tests/print-summary-full/Makefile, gcovr/tests/print-summary-full/README, gcovr/tests/print-summary-full/main.cpp, gcovr/tests/print-summary-full/reference/clang-10/coverage.txt, gcovr/tests/print-summary-full/reference/gcc-5/coverage.txt, gcovr/tests/print-summary-full/reference/gcc-8/coverage.txt, gcovr/tests/print-summary/reference/clang-10/coverage.txt, gcovr/tests/print-summary/reference/gcc-5/coverage.txt, gcovr/tests/print-summary/reference/gcc-8/coverage.txt, gcovr/writer/summary.py
The decission summary is missing and the calls summary is printed even if the values aren't gathered.
This PR fixes the summary report by:
- Only print call coverage summary if option `--calls` is given.
- Print decision summary coverage if option `--decisions` is given.
Closes #745
=> Fix summary report

CHANGELOG.rst, gcovr/__main__.py, gcovr/utils.py
Without threads the logging isn't changed. If more than one thread is used the message looks like this:
```
(DEBUG) - Thread-2 - Parsing coverage data for file /Users/Shared/Informatik/GitHub/gcovr/gcovr/tests/nested/subdir/A/file2.cpp
(DEBUG) - MainThread - Gathered coveraged data for 8 files
```
Closes #751
=> Add thread information to logging

CHANGELOG.rst, noxfile.py
With a interactive shell you can use Ctrl-C to interrupt the docker call.
=> Use interactive terminal for docker if stdin is a tty.

CHANGELOG.rst, gcovr/formats/gcov/read.py, gcovr/formats/html/write.py, gcovr/utils.py
Respect the case where gcov returns an absolute path to the source files.
Add type hints and reorder arguments to give all files first.
=> Respect absolute paths from gcov output.

CHANGELOG.rst, CONTRIBUTING.rst, noxfile.py
If a bug for `gcc` OR `clang` is fixed it's time consuming to run allways the tests for all compilers. This PR introduces the additional compilers `gcc` and `clang` which runs all versions of the specified compiler.
=> Add task for compiler familiy

CHANGELOG.rst, admin/Dockerfile.qa, noxfile.py
When running `setup.py` directly following message is printed:
Please avoid running ``setup.py`` directly.
Instead, use pypa/build, pypa/installer or other
standards-based tools.
See https://blog.ganssle.io/articles/2021/10/setup-py-deprecated.html for details.
=> Use `build` instead of calling `setup.py` directly.

noxfile.py
With the latest version 6.0.0 we get following error:
```
9459 INFO: Including run-time hook '/gcovr/.nox-containerized.gcc-8.uid_1001/bundle_app/lib/python3.8/site-packages/PyInstaller/hooks/rthooks/pyi_rth_pkgres.py'
9476 INFO: Looking for dynamic libraries
Traceback (most recent call last):
...
File "/usr/lib/python3.8/pathlib.py", line 1198, in stat
return self._accessor.stat(self)
PermissionError: [Errno 13] Permission denied: '/root/.local/lib/python3.8/site-packages'
nox > Command pyinstaller --distpath . --workpath ./pyinstaller --specpath ./pyinstaller --onefile --collect-all gcovr.formats -n gcovr ../scripts/pyinstaller_entrypoint.py failed with exit code 1
```
[no changelog]
=> Pin pyinstaller version

CHANGELOG.rst, gcovr/formats/gcov/read.py, gcovr/merging.py
Use option `--merge-mode-functions` also when merging coverage data. The default value for the merge option is removed from the functions making it now a required argument.
Closes #841
=> Use options when merging coverage data (#841)

gcovr/tests/test_gcovr.py
The clang based gcc which is used on MacOs throws some errors in newer versions. Also the variable IS_CLANG wasn't set correct because CC is set to gcc and CC_REFERENCE to clang-<version>.
[no changelog]
=> Exclude more test if executed on MacOs

README.rst
Add a badge to the main readme to see the documentation status on Readthedocs.
[no changelog]
=> Add status badge for documentation

.github/workflows/deploy.yml, .github/workflows/test.yml, CHANGELOG.rst
Fix the warnings in the pipeline:
```
Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: actions/checkout@v3. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.
```
=> Update version of pipeline actions

CHANGELOG.rst, gcovr/__main__.py, gcovr/configuration.py, gcovr/utils.py, noxfile.py, setup.py
Update the logging to use a coloured output if running in a TTY or the user forced it by setting `--force-color` in the CLI or by defining the environment variable `FORCE_COLOR` as described in http://force-color.org.
In the pipeline the color is forced (introduced for nox by #698). If a test is failing we get now a coloured output of gcovr execution.
=> Use coloured logging in a TTY

.github/workflows/deploy.yml, CHANGELOG.rst
Add pipeline job to apply tag if new version is bumped to main branch.
A tag is always created but only pushed if there is no suffix after the version number.
=> Add tagging to pipeline

CHANGELOG.rst, gcovr/__main__.py, gcovr/tests/gcov-exclude/Makefile, gcovr/tests/gcov-exclude/reference/clang-10/coverage.lcov, gcovr/tests/gcov-exclude/reference/clang-10/coveralls.json, gcovr/tests/gcov-exclude/reference/gcc-5/coverage.lcov, gcovr/tests/gcov-exclude/reference/gcc-5/coveralls.json, gcovr/tests/gcov-exclude/reference/gcc-8/coverage.lcov, gcovr/tests/gcov-exclude/subdir/A/C/D/File6.cpp, gcovr/tests/gcov-exclude/subdir/A/C/file5.cpp, gcovr/tests/gcov-exclude/subdir/A/File2.cpp, gcovr/tests/gcov-exclude/subdir/A/File4.cpp, gcovr/tests/gcov-exclude/subdir/A/file1.cpp, gcovr/tests/gcov-exclude/subdir/A/file3.cpp, gcovr/tests/gcov-exclude/subdir/A/file7.cpp, gcovr/tests/gcov-exclude/subdir/B/main.cpp, gcovr/tests/simple1/Makefile, gcovr/tests/test_args.py, gcovr/tests/test_gcovr.py, noxfile.py
If theist is executed locally and the environment `USE_COVERAGE=true`  HTML coverage report is generated after executing the tests.
=> Improve coverage and generate report locally

.github/workflows/test.yml, CHANGELOG.rst, noxfile.py, tests/decisions/reference/gcc-13-Darwin/coverage.json, tests/gcc-abspath/Makefile, tests/test_gcovr.py
Add MacOs to the test matrix on GitHub.
To get the tests working the selection of the compiler and the reference data which is done in the noxfile needs to be improved. Now you need to set CC to the name of the executable which shall be used and from this executable the version is selected.
The docker test pointed out that the detection of the gcc version wasn't correct. There can be a number after the version:
```
gcc-5 (Ubuntu/Linaro 5.5.0-12ubuntu1) 5.5.0 20171010
```
=> Add macOS to GitHub tests

.github/workflows/test.yml, CHANGELOG.rst
The update of the installed packages takes quite long and is failing.
=> Do not update dependencies on MacOs

CHANGELOG.rst, gcovr/__main__.py, gcovr/utils.py, tests/simple1/Makefile
If gcovr is executed in Azure pipeline or GitHub actions a additional
logging handler is installed which prints warning and error  message
in a format detected by the CI system.
=> Add log messages which are captured by the CI

setup.cfg
The timeout of 60 seconds seems to be too less for some tests on MacOs.
[no changelog]
=> Increase timeout of pytest because of MacOs runner

gcovr/utils.py
Calling basicConfig without a handler installs a default handler which results in printing the message twice with different formats.
[no changelog]
=> Set the handler with the basic config

setup.py
According to https://packaging.python.org/en/latest/specifications/version-specifiers/#developmental-releases the used local version identifier is described as:
Local version identifiers are used to denote fully API (and, if
applicable, ABI) compatible patched versions of upstream projects.
According to https://packaging.python.org/en/latest/specifications/version-specifiers/#developmental-releases we should use a development version specifier. The version identifier is extended by the build time.
[no changelog]
=> Use development version instead of local ones

.github/workflows/test.yml, CHANGELOG.rst, gcovr/merging.py, noxfile.py
#923 pointed out that there is a problem building the standalone executable with Python 3.12.
The application aborts with following message: 
```
Traceback (most recent call last):
File "pyinstaller_entrypoint.py", line 22, in <module>
ModuleNotFoundError: No module named 'gcovr.__main__'
[267] Failed to execute script 'pyinstaller_entrypoint' due to unhandled exception!
```
=> Fix building executable with python 3.12

.github/workflows/test.yml, tests/test_gcovr.py
The test is not compilable with gcc on MacOs. The native compiler is working
[no changelog]
=> Turn off coexisting_object_directories tests for MacOs with gcc

.github/workflows/test.yml, .gitignore, noxfile.py
Fix the pip cache directory to cache the data on all OS.
Activate beta feature of Docker to cache the builds on GitHub. This improves the time needed to build the docker image, e.g. a second run for `gcc-10` image needs 17s instead of 1m 22s.
[no changelog]
=> Fix cache in pipeline

.github/workflows/deploy.yml, .github/workflows/test.yml, CHANGELOG.rst
- Skip coverage upload if executed in a fork. This will always fail because of missing token.
- Only execute pipeline if pushed on main and add button to execute workflow manual.
=> Improve pipeline for main and fork

.github/workflows/deploy.yml, .github/workflows/test.yml, CHANGELOG.rst
For the PR the `opened` and the `edited` is triggered. Since we need the `edited` to be triggered on comment changes we remove the `opened` trigger.
=> Do not trigger pipeline twice for new PR

CHANGELOG.rst, doc/source/conf.py, gcovr/decision_analysis.py
https://github.com/gcovr/gcovr/security/code-scanning/1: Changed to be less greedy.
Also extended Spynx configuration with role to shorten security links.
=> Fix code scanning alert

CHANGELOG.rst, doc/source/conf.py
Read The Docs has deprecated Sphinx context injection and we need to do the configuration on our own.
Add settings from https://github.com/readthedocs/sphinx-build-compatibility/blob/main/sphinx_build_compatibility/extension.py to our configuration.
Closes #934
=> Update Sphinx config

.github/workflows/deploy.yml, .github/workflows/test.yml, CHANGELOG.rst
Revert #931.
This seems to be only an issue for maintainers. PRs from otheres need to be triggered on `opened`.
[no changelog]
=> Trigger again pipeline on PR open

CHANGELOG.rst, gcovr/formats/gcov/read.py
I try to fix next message
```
(ERROR) GCOV produced the following errors processing /home/gitlab-runner/disk/builds/HafKdfP1/0/PT/hiper100re/build/contrib/libre2/CMakeFiles/re2.dir/util/strutil.cc.gcda:
Trouble processing '/home/gitlab-runner/disk/builds/HafKdfP1/0/PT/hiper100re/build/contrib/libre2/CMakeFiles/re2.dir/util/strutil.cc.gcda' with working directory '/home/gitlab-runner/disk/builds/HafKdfP1/0/PT/hiper100re'.
Stdout of gcov was >>None<< End of stdout    (<- Here)
Stderr of gcov was >>None<< End of stderr   (<- Here)
Exception was >>GCOV returncode was 5.<< End of stderr
```
We lose stdout and stderr when return code of gcov is not 0 or 6, so all useful information lost ( I used strace tool to get messages).
Now, stdout and stderr are saved in object for sure
=> Don't loose stderr and stdout of gcovr for non-zero return code

LICENSE.txt, README.rst, admin/bump_version.py, doc/source/license.rst
Use the license template for the `BSD 3-Clause License` from GitHub.
Instead of having the copyright notice in README.rst, license.rst and LICENSE.txt all locations reference the section in the documentation with the included LICENSE.txt.
From the README.rst rendered by GitHub we now link to the latest documentation instead of having the copyright notice and a textual reference to the other files.
[no changelog]
=> Add license type and update documentation

.github/workflows/CI.yml, CHANGELOG.rst
There is a deprecation warning and brew installation is failing since today.
```
Warning: You are using macOS 12.
We (and Apple) do not provide support for this old version.
```
=> Remove test on MacOs 12 because of installation issues

noxfile.py
With the new image the value for `fullPage` must be a boolean and not a string.
[no changelog]
=> Fix export payload

CHANGELOG.rst, gcovr/exclusions/__init__.py
If a compiler generated function is excluded and a line is assigned to this function the line is excluded as well.
=> Exclude also lines belonging to excluded functions

CHANGELOG.rst, gcovr/formats/gcov/read.py
This PR adds a check for the format version mentioned inside the gcov JSON file.
Closes #995
=> Add file version check for external files

CHANGELOG.rst, gcovr/utils.py
If on Windows (case insensitive filesystems) a source folder is removed before running `gcovr` it results in a crash when the file case is fixed.
Closes #994
=> Fix file not found exception

.github/workflows/CI.yml, .github/workflows/upload_coverage.yml, CHANGELOG.rst, gcovr/formats/lcov/__init__.py, gcovr/formats/lcov/write.py, tests/nested/Makefile, tests/nested/reference/clang-10/coverage.lcov, tests/nested/reference/clang-13/coverage.lcov, tests/nested/reference/gcc-14/coverage.lcov, tests/nested/reference/gcc-5/coverage.lcov, tests/nested/reference/gcc-8/coverage.lcov
Add option to generate LCOV format produced by version 1.x of LCOV tool because this is supported by most CI/CD systems for uploading coverage data.
=> Support lcov v1 format

CHANGELOG.rst, noxfile.py, setup.py
Timestamp seems to be read twice and differs in 1 second. Pip complains about name mismatch of wheel file.
=> Set the timestamp as environment

CHANGELOG.rst, gcovr/exclusions/__init__.py, gcovr/exclusions/utils.py, tests/excl-function/reference/gcc-14/coverage.json, tests/excl-line-branch/reference/gcc-14/coverage.json, tests/html-themes-github/reference/gcc-10/coverage.call_decisions.main.cpp.118fcbaaba162ba17933c7893247df3a.html, tests/html-themes-github/reference/gcc-10/coverage.calls.main.cpp.118fcbaaba162ba17933c7893247df3a.html, tests/html-themes-github/reference/gcc-11/coverage.call_decisions.main.cpp.118fcbaaba162ba17933c7893247df3a.html, tests/html-themes-github/reference/gcc-11/coverage.calls.main.cpp.118fcbaaba162ba17933c7893247df3a.html, tests/html-themes-github/reference/gcc-13-Darwin/coverage.call_decisions.main.cpp.118fcbaaba162ba17933c7893247df3a.html, tests/html-themes-github/reference/gcc-13-Darwin/coverage.calls.main.cpp.118fcbaaba162ba17933c7893247df3a.html, tests/html-themes-github/reference/gcc-5/coverage.call_decisions.main.cpp.118fcbaaba162ba17933c7893247df3a.html, tests/html-themes-github/reference/gcc-5/coverage.calls.main.cpp.118fcbaaba162ba17933c7893247df3a.html, tests/html-themes-github/reference/gcc-6/coverage.call_decisions.main.cpp.118fcbaaba162ba17933c7893247df3a.html, tests/html-themes-github/reference/gcc-6/coverage.calls.main.cpp.118fcbaaba162ba17933c7893247df3a.html, tests/html-themes-github/reference/gcc-8-Windows/coverage.call_decisions.main.cpp.118fcbaaba162ba17933c7893247df3a.html, tests/html-themes-github/reference/gcc-8-Windows/coverage.calls.main.cpp.118fcbaaba162ba17933c7893247df3a.html, tests/html-themes-github/reference/gcc-8/coverage.call_decisions.main.cpp.118fcbaaba162ba17933c7893247df3a.html, tests/html-themes-github/reference/gcc-8/coverage.calls.main.cpp.118fcbaaba162ba17933c7893247df3a.html
- When lines are excluded, they should remove coverage for branches, calls and conditions.
- This ensures consistency of reporting for future enhancements to exclusion metrics
#988
=> Fix line exclusion

CHANGELOG.rst, doc/source/guide/gcov_parser.rst, gcovr/formats/gcov/__init__.py, gcovr/formats/gcov/parser.py, gcovr/formats/gcov/read.py
https://github.com/gcovr/gcovr/pull/903#issuecomment-2444895806 pointed out that the threshold of 2**32 needs to be increased. This PR adds an option to increase it or to turn off the detection at all.
=> Add option for suspicious hits

doc/source/faq.rst, src/gcovr/__main__.py
As described in https://github.com/gcovr/gcovr/issues/1042#issuecomment-2564490670, this PR removes the section about the decision coverage from the FAQ and adds a log message if `--decision` is used.
[no changelog]
=> Update docs and add a log message

doc/source/output/html.rst
Point to real folder now the sources files have been moved to `src/`.
[no changelog]
=> Update link now sources have been moved to src/ folder

CHANGELOG.rst, doc/examples/example_cmake.sh, noxfile.py, src/gcovr/formats/gcov/parser.py, src/gcovr/formats/gcov/parser/common.py, src/gcovr/formats/gcov/parser/json.py, src/gcovr/formats/gcov/parser/text.py, src/gcovr/formats/gcov/read.py, tests/test_gcov_parser.py
Since GCC 14, gcov outputs a json file instead the usual text file. The parsing code didn't implement the logic necessary for ignoring negative hits.
This PR:
- Adds the missing logic
- Splits the body of `process_gcov_json_data` to facilitate testing
- Adds tests covering the three modes of reporting (exception, warning, one warning per file)
=> Add support for ignoring negative hit count in gcov json parser

.github/workflows/CI.yml, .github/workflows/gcovr-ci-job.yml, CHANGELOG.rst, noxfile.py, src/gcovr/options.py
Fix warning `Deprecated config key None used, please use 'txt-metric=branch' instead.` if `txt-metric="branch"` is used in config file.
Fixes #1064, #1060
=> Fix warning about deprecated config key `None`

.github/workflows/CI.yml
The Ubuntu 20.04 runner image will be fully unsupported by April 1, 2025.
[no changelog]
=> Replace Ubuntu 20.04 runners

.github/workflows/gcovr-ci-job.yml, README.rst, doc/source/conf.py, doc/source/cookbook.rst, doc/source/output/cobertura.rst, doc/source/output/html.rst, doc/source/output/sonarqube.rst, noxfile.py
The check sometimes can't reach the target. To reduce the target request the links are now only checked during deployment stage.
[no changelog]
=> Only check the links during deployment stage

.github/workflows/CI.yml, CHANGELOG.rst, doc/source/conf.py, src/gcovr/formats/gcov/read.py
The error message `xxx.gcno:version 'B42*', prefer 'B33*'` is now detected and handled by gcovr instead of trying next working directory.
=> Abort on version missmatch between gcc/gcov

CHANGELOG.rst, noxfile.py
When running the standalone application the following warning is printed:
PyInstaller/loader/pyimod02_importers.py:384: UserWarning: pkg_resources is deprecated as an API
=> Fix deprecation warning in standalone application

.github/workflows/CI.yml
Split the release into dedicated jobs for creating the tag, publishing the GH release and uploading the distribution files.
[no changelog]
=> Split release jobs

CHANGELOG.rst, src/gcovr/formats/gcov/parser/json.py, tests/decisions/reference/gcc-14-Windows/coverage.json, tests/decisions/reference/gcc-14/coverage.json
In gcov JSON report there can be files without lines and function, e.g.:
```json
{
"file": "/<…>/d4f0bc5a/13edd1ef.h",
"functions": [],
"lines": []
},
```
This files are now ignored and not added to the data model.
=> Ignore empty data from gcov JSON report

.github/workflows/CI.yml, noxfile.py
- The empty line after a sub list is removed.
- The job summary is now also generated in nox session:
- Version added without the leading spaces.
- Issue links replaced by real links because #xxx is not rendered in job summary.
- Compare gcovr version with current release ID if not under development.
[no changelog]
=> Improve release notes and job summary

CHANGELOG.rst, doc/source/output/clover.rst, doc/source/output/cobertura.rst, doc/source/output/coveralls.rst, doc/source/output/csv.rst, doc/source/output/html.rst, doc/source/output/jacoco.rst, doc/source/output/lcov.rst, doc/source/output/markdown.rst, doc/source/output/sonarqube.rst, doc/source/output/txt.rst, src/gcovr/formats/html/write.py, src/gcovr/formats/json/read.py, src/gcovr/utils.py, tests/.gitignore, tests/decisions/Makefile, tests/html-single-page/Makefile, tests/virtual-classes/Makefile
If the last suffix of the output is `.gz` it will be saved as zipped file.
The JSON report (trace file) used as input can also be a zipped file (`.json.'gz).
=> Add support to save zipped report

CHANGELOG.rst, src/gcovr/formats/gcov/__init__.py, src/gcovr/formats/gcov/workers.py, src/gcovr/logging.py, tests/test_config.py
If the value for `-j` is 0, the number of CPUs is used. If it is negative the it means "all but N CPUs".
E.g. if we have 8 CPUs and set the value to -1 we use 7 processes.
Related #1145
=> Extend option `-j` to support "all but N CPUs"
