scripts/gcovr

Solves issue #74 
Now there's a branch column between line and execution count. Green ticks show taken branch, red crosses show not taken branch.

Added branches taken/not taken info into HTML.

---

README.md
doc/guide.txt

Not sure this is the best way of advertising this but let's open the discussion.
c.f. #202

Add warning about using gcovr as a single script

---

.travis.yml
appveyor.yml
gcovr/tests/test_gcovr.py

Use codecov service to get coverage information on gcovr

---

gcovr/__main__.py

`options.root` can’t be `None`
Its default value is `'.'` since commit aaa733eaa9b5656058277c56de53344cd75e3dd8

Remove unreachable code

---

CHANGELOG.rst
doc/source/conf.py

This is work in progress. It should not be merged yet, since it is based on #248 and contains its commit also.
Only the last commit is relevant for this.

doc: Link to github issues from changelog page 

---

gcovr/summary_generator.py
gcovr/tests/exclude-directories-relative/README
gcovr/tests/exclude-relative/README
gcovr/tests/print-summary/Makefile
gcovr/tests/print-summary/README
gcovr/tests/print-summary/main.cpp
gcovr/tests/print-summary/reference/coverage.txt

Also fix test descriptions in README files.

Test `--print-summary` option.

---

.gitignore
gcovr/tests/.gitignore
gcovr/tests/conftest.py
gcovr/tests/test_gcovr.py

- Add option --update_reference to update the reference data if there are differences.
- Add option --skip_clean to keep test output.

Extend tests to use an unified diff in the assert #374

---

gcovr/tests/test_gcovr.py

Add support for list of output pattern in test.

---

AUTHORS.txt
CHANGELOG.rst
gcovr/gcov.py

Fix gcov command splitting to allow spaces in path

---

gcovr/coveralls_generator.py
gcovr/tests/test_gcovr.py

Fix for #328 on master.
The environment GCOVR_TEST_SUITE has highest priority, ignoring the used CI.
Set PR in the data only if the environment is set to a value.

Fix Appveyor test for coveralls

---

gcovr/tests/add_coverages/reference/coverage.main.cpp.118fcbaaba162ba17933c7893247df3a.html
gcovr/tests/config-output/reference/coverage.html
gcovr/tests/dot/reference/coverage.main.cpp.d0d5fc20837f40fa4765af5e07f5d1b9.html
gcovr/tests/exclude-throw-branches/reference/coverage-excl-throw.main.cpp.118fcbaaba162ba17933c7893247df3a.html
gcovr/tests/exclude-throw-branches/reference/coverage-throw.main.cpp.118fcbaaba162ba17933c7893247df3a.html
gcovr/tests/html-css/reference/coverage.html
gcovr/tests/html-default/reference/coverage.css
gcovr/tests/html-tab-size-2/reference/coverage.css
gcovr/tests/html-themes/reference/coverage.blue.css
gcovr/tests/html-themes/reference/coverage.blue.main.cpp.118fcbaaba162ba17933c7893247df3a.html
gcovr/tests/html-themes/reference/coverage.green.css
gcovr/tests/html-themes/reference/coverage.green.main.cpp.118fcbaaba162ba17933c7893247df3a.html
gcovr/tests/linked/reference/coverage.main.cpp.13fb8fc771195717481a98e084ed0848.html
gcovr/tests/nested/reference/coverage.css
gcovr/tests/nested/reference/coverage.main.cpp.9ddfb860fa969e91a7bb17e903455bce.html
gcovr/tests/nested2-use-existing/reference/coverage.main.cpp.9ddfb860fa969e91a7bb17e903455bce.html
gcovr/tests/nested2/reference/coverage.css
gcovr/tests/nested2/reference/coverage.main.cpp.9ddfb860fa969e91a7bb17e903455bce.html
gcovr/tests/simple1-stdout/reference/coverage.html
gcovr/tests/simple1/reference/coverage-details-includecss.html
gcovr/tests/simple1/reference/coverage-details-includecss.main.cpp.118fcbaaba162ba17933c7893247df3a.html
gcovr/tests/simple1/reference/coverage-summary-includecss.html
gcovr/tests/sort-percentage/reference/coverage.main.cpp.118fcbaaba162ba17933c7893247df3a.html
gcovr/tests/sort-uncovered/reference/coverage.main.cpp.118fcbaaba162ba17933c7893247df3a.html
gcovr/tests/threaded/reference/coverage.main.cpp.9ddfb860fa969e91a7bb17e903455bce.html
gcovr/tests/update-data/reference/coverage.update-data.h.522c29cd66298f97fb9ff5a561c844e0.html
requirements.txt

Fix version to the version released today because the HTML output is changed and test fails.

Pin pygments version to 2.7.0 and update test data

---

CHANGELOG.rst
gcovr/configuration.py
gcovr/tests/html-no-syntax-highlighting/Makefile
gcovr/tests/nested3/Makefile

Change option as mentioned in #402

Use negative option to turn of syntax highlighting

---

.gitbugtraq
CHANGELOG.rst
doc/source/guide.rst

Add hint from discussion in #428.

Extend documentation for coveralls

---

gcovr/tests/.gitattributes

Also remove Makefile and CSS files.

Fix additional GitHub language statistics

---

.github/workflows/test.yml

Split commands to get separate logs in CI.

Split build and run of Docker container.

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_request.md
.github/ISSUE_TEMPLATE/general_question.md
CHANGELOG.rst

Update issue templates

---

.github/workflows/test.yml

Extend check for selected milestone to remind project member to add PR to the current milestone.
[no changelog]

Check if milestone is added to PR.

---

gcovr/writer/html.py

Fix spelling

---

.github/workflows/test.yml
CONTRIBUTING.rst
Makefile
README.rst
doc/source/guide.rst

- Update the docs for running tests as mentioned in #325.
- Rename make target `format` to `check-format` and add it to the docs.
[no changelog]

Update docs and test.

---

CHANGELOG.rst

fix spelling in changelog

---

CHANGELOG.rst
gcovr/__main__.py
gcovr/tests/simple1/Makefile

Add message suggested in #98.
Closes #98

Add error to STDOUT --fail-under-line or --fail-under-branch.

---

CHANGELOG.rst
gcovr/tests/test_gcovr.py

Change to be the same as for the unified diff.

Change test and reference for XML diff.

---

CHANGELOG.rst
gcovr/gcov.py

Deactivate gcov localization.

---

.github/workflows/test.yml
CHANGELOG.rst
Makefile

Also reduce the test matrix for GitHub actions.

Add option to run all compilers

---

CHANGELOG.rst
noxfile.py

As mentioned in #465 for GitHub Actions this is a general implementation of testing the installation of the wheel.

Add test to install wheel after build.

---

noxfile.py

Fix wrong name in noxfile.py.
[no changelog]

Fix option to reuse virtual environment.

---

admin/add_copyright.py
gcovr/gcov.py
gcovr/gcov_parser.py
gcovr/writer/json.py
noxfile.py

There was a `not` missing. The already formatted files where not checked.
Prepared copyright update to also patch runtime print in `__main__.py`.
[no changelog]

Fix black check and prepare copyright update

---

admin/add_copyright.py

As mentioned in #558 there is a problem in the detection of the line change. This PR fixes the issue by adding a second handler and working with a list of handlers.
[no changelog]

Fix add_copyright.

---

gcovr/gcov_parser.py
gcovr/tests/test_args.py
gcovr/writer/summary.py

As requested in #540 here are the changes.
[no changelog]

Fix regressions from #540.

---

gcovr/gcov_parser.py
noxfile.py

Adapt code to black 22.1.0 and pin the version.
[no changelog]

Pin version of black.

---

CHANGELOG.rst
gcovr/writer/html.py

Fix sanity as mentioned in https://github.com/gcovr/gcovr/issues/519#issuecomment-946852982.
Closes #519

Fix sanity check in HTML generator.

---

gcovr/tests/test_gcovr.py

Apply review remarks after merge.

---

CHANGELOG.rst

Remove leading space in changelog lists.

---

CONTRIBUTING.rst
doc/source/guide/exclusion-markers.rst
gcovr/configuration.py

Some parts where not mentioned in the docs.
[no changelog]

Update docs with new options

---

CHANGELOG.rst
admin/bump_version.py
noxfile.py

Bump version also to documentation files:
- The references used in the added, removed and deprecated parts.
- The headline in the CHANGELOG.rst.
[no changelog]

Update references to NEXT version with current version in documentation.

---

CHANGELOG.rst
gcovr/gcov.py

Add exception handler to get more infos on gcov failures as mentioined in #587.

Add exception handling for processing of files.

---

doc/source/conf.py

Fix Sphinx generation (language must not be `None`.

---

CHANGELOG.rst
gcovr/gcov.py
gcovr/tests/test_gcovr.py

If `gcov` exits with a value != 0 raise an exception.
Closes #254

Do not ignore returncode of `gcov`.

---

doc/examples/example_cobertura.sh
gcovr/tests/cobertura.coverage-04.dtd

CI start failing with:
```
error : Unknown IO error
example_cobertura.xml:2: warning: failed to load external entity "http://cobertura.sourceforge.net/xml/coverage-04.dtd"
<!DOCTYPE coverage SYSTEM 'http://cobertura.sourceforge.net/xml/coverage-04.dtd'
^
example_cobertura.xml:3: validity error : Validation failed: no DTD found !
```
[no changelog]

Store DTD for cobertura for validation.

---

.github/workflows/deploy.yml
.github/workflows/test.yml
CHANGELOG.rst
doc/examples/test_examples.py
gcovr/tests/test_gcovr.py
gcovr/writer/csv.py
noxfile.py

This PR replaces the copy command used for updating the reference data and create the reference file with the scrubbed data.

Use scrubbed data for update of reference

---

.github/workflows/deploy.yml
CHANGELOG.rst
CONTRIBUTING.rst
noxfile.py

Add a separate session for flake8 and run the sessions flake8 and black in session lint.

Split lint session

---

.github/workflows/deploy.yml
.github/workflows/test.yml
.gitignore
CHANGELOG.rst
gcovr/tests/test_args.py
noxfile.py

Since the deprecated python uploader is removed from pypi.org this PR replaces the uploader as described [here](https://docs.codecov.com/docs/deprecated-uploader-migration-guide#python-uploader).

Replace deprecated codecov python uploader

---

CHANGELOG.rst
admin/Dockerfile.qa

Fix Dockerfile.qa to avoid uid conflicts

---

CHANGELOG.rst
gcovr/__main__.py
gcovr/coverage.py
gcovr/formats/gcov/read.py
gcovr/formats/html/write.py
gcovr/tests/filter-relative-lib-from-unfiltered-tracefile/Makefile
gcovr/tests/filter-relative-lib-from-unfiltered-tracefile/setup.cmd
gcovr/tests/filter-relative-lib/Makefile
gcovr/tests/filter-relative-lib/setup.cmd
gcovr/tests/linked/Makefile
gcovr/tests/linked/setup.cmd
gcovr/tests/simple1-drive-subst/Makefile
gcovr/tests/simple1-drive-subst/reference/gcc-8-Windows/coverage-details-linkcss.main.cpp.118fcbaaba162ba17933c7893247df3a.html
gcovr/tests/simple1-drive-subst/wrap.cmd
gcovr/tests/symlink-root/Makefile
gcovr/tests/symlink-root/setup.cmd
gcovr/utils.py

The windows test was failing because of a update of the runner. It seems that the `cmd.exe /C "..."` doesn't work anymore. Maybe this is a problem with the quotes. This PR replaces the quoted command with a call to a batch script.
Add additional logging which helped finding the error.

Fix substed working dir on windows

---

gcovr/configuration.py
gcovr/coverage.py
gcovr/formats/csv/write.py
gcovr/formats/html/write.py
gcovr/formats/json/write.py
gcovr/formats/txt/write.py

Update documentation option --branch

---

CHANGELOG.rst
gcovr/configuration.py
gcovr/tests/config-output/Makefile
gcovr/tests/config-output/config/gcovr.error.config

Optional choices where treated as boolean value even if there where choices defined.
Closes #809.

Fix reading config files

---

doc/source/output/json.rst

Add entries to documentation (missed in #822).
[no changelog]

Update documentation with new entries from #822

---

CHANGELOG.rst
noxfile.py

Add session to import the data from a ZIP file (e.g. generated in the pipeline).

Add nox session to update reference from zip

---

.github/workflows/deploy.yml
.github/workflows/test.yml
CHANGELOG.rst
admin/Dockerfile.qa
doc/source/installation.rst
gcovr/coverage.py
gcovr/formats/html/write.py
gcovr/utils.py
noxfile.py
setup.cfg
setup.py

This PR drops support as suggested in #867.

Drop support for python 3.7

---

.readthedocs.yml

Add configuration to fix documentation build.
Closes #870 
[no changelog]

Add configuration for readthedocs

---

CHANGELOG.rst
admin/Dockerfile.qa

Cache tha apt cache to improve build performance of the images. Use heredocs for better readability.

Cache the apt cache of the Docker build

---

CHANGELOG.rst
README.rst
doc/examples/example_clover.sh
doc/examples/example_clover.xml
doc/examples/example_cobertura.sh
doc/source/guide/multiple-outputs.rst
doc/source/index.rst
doc/source/output/clover.rst
doc/source/output/cobertura.rst
doc/source/output/index.rst
doc/source/output/jacoco.rst
gcovr/formats/__init__.py
gcovr/formats/clover/__init__.py
gcovr/formats/clover/write.py
gcovr/formats/cobertura/write.py
gcovr/tests/.gitignore
gcovr/tests/clover.xsd
gcovr/tests/nested/Makefile
gcovr/tests/nested/reference/gcc-5/clover.xml
gcovr/tests/nested/reference/gcc-8/clover.xml
gcovr/tests/simple1/Makefile
gcovr/tests/simple1/reference/gcc-5/clover.xml
gcovr/tests/simple1/reference/gcc-8/clover.xml
gcovr/tests/test_gcovr.py

Add support for Clover XML format as requested in #865.
Closes #865.

Add support for clover format

---

AUTHORS.txt
CHANGELOG.rst
gcovr/configuration.py
tests/test_args.py

Fixes https://github.com/gcovr/gcovr/issues/909

Bugfix: Erroneous deprecation warning

---

.github/actions/setup-python/action.yml
.github/actions/setup-runner/action.yml
.github/workflows/deploy.yml
.github/workflows/gcovr-ci-job.yml
.github/workflows/test.yml
.vscode/tasks.json
CHANGELOG.rst
noxfile.py

Add a reusable workflow step and use the same job for VMs and container tests. This is the first step for merging the test and the deploy workflow step.
Related: #941

Use the same workflow for VMs and container check

---

.github/actions/setup-runner/action.yml
.github/workflows/CI.yml
.github/workflows/gcovr-ci-job.yml
.github/workflows/upload_coverage.yml
CHANGELOG.rst
README.rst
cspell.json

Because there are several problems witch uploading the coverage report to Codecov in the last months this PR is adding Codacy to the CI.

Add Codacy to CI

---

.github/workflows/gcovr-ci-job.yml
.github/workflows/upload_coverage.yml
.vscode/tasks.json
CHANGELOG.rst
CONTRIBUTING.rst
admin/bump_version.py
doc/examples/test_examples.py
gcovr/configuration.py
gcovr/coverage.py
gcovr/formats/clover/write.py
gcovr/formats/cobertura/read.py
gcovr/formats/cobertura/write.py
gcovr/formats/coveralls/write.py
gcovr/formats/gcov/parser.py
gcovr/formats/gcov/read.py
gcovr/formats/gcov/workers.py
gcovr/formats/html/write.py
gcovr/formats/jacoco/write.py
gcovr/formats/json/read.py
gcovr/formats/sonarqube/write.py
gcovr/formats/txt/write.py
gcovr/merging.py
gcovr/options.py
gcovr/utils.py
noxfile.py
pyproject.toml
tests/test_gcovr.py
tests/test_html_generator.py

Add bandit tool to the linters and fix all issues.
This tool is configured on Codacy and should also be available for local execution.

Add bandit for code checking

---

.github/workflows/upload_coverage.yml
gcovr/formats/base.py
gcovr/formats/clover/__init__.py
gcovr/formats/cobertura/__init__.py
gcovr/formats/coveralls/__init__.py
gcovr/formats/csv/__init__.py
gcovr/formats/gcov/__init__.py
gcovr/formats/html/__init__.py
gcovr/formats/jacoco/__init__.py
gcovr/formats/json/__init__.py
gcovr/formats/lcov/__init__.py
gcovr/formats/sonarqube/__init__.py
gcovr/formats/txt/__init__.py

Fix pylint issues from Codacy and split find command for coverage upload on Codecov.
[no changelog]

Fix pylint issues

---

README.rst

Replace Codecov badge with Codacy badge and reorder the badges.
[no changelog]

Update status badges

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_request.md
.github/ISSUE_TEMPLATE/general_question.md
cspell.json
gcovr/formats/gcov/parser.py
gcovr/utils.py
noxfile.py

Fix semgrep issues from Codacy.
[no changelog]

Fix semgrep issues

---

.github/workflows/gcovr-ci-job.yml
admin/bump_version.py
doc/examples/test_examples.py
gcovr/configuration.py
gcovr/coverage.py
gcovr/formats/base.py
gcovr/formats/cobertura/read.py
gcovr/formats/cobertura/write.py
gcovr/formats/gcov/parser.py
gcovr/formats/gcov/workers.py
gcovr/formats/json/read.py
gcovr/formats/json/write.py
gcovr/merging.py
gcovr/options.py
gcovr/utils.py
noxfile.py
tests/excl-branch/Makefile
tests/excl-line-branch/Makefile
tests/excl-line-custom/Makefile
tests/excl-line/Makefile
tests/nested/Makefile
tests/nested/reference/clang-10/clover.xml
tests/nested/reference/gcc-5/clover.xml
tests/source_from_pipe/.gitignore
tests/source_from_pipe/Makefile
tests/test_args.py
tests/test_gcovr.py

Improve the test coverage to increase the quality.
[no changelog]

Improve quality and coverage

---

.github/workflows/upload_coverage.yml
CHANGELOG.rst

Remove Codecov from pipeline and only use Codacy.

Remove codecov

---

CHANGELOG.rst
gcovr/coverage.py
gcovr/exclusions/__init__.py
gcovr/exclusions/utils.py
noxfile.py

Fix access of function coverage list

---

CHANGELOG.rst
gcovr/coverage.py

Only print info on the first undefined block number in data model

---

AUTHORS.txt
CHANGELOG.rst
gcovr/formats/gcov/read.py

Fixes https://github.com/gcovr/gcovr/issues/996

Fix error reporting bug

---

.github/workflows/CI.yml
.github/workflows/upload_coverage.yml

Use all supported formats for Codacy upload
[no changelog]

Upload coverage data of nested testcase

---

CHANGELOG.rst
gcovr/coverage.py
noxfile.py

- Added excluded flags to some coverage metrics
- Changed code to set the flag instead of wiping things for branches, calls and conditions
- Adjusted reporting code to ignore now present but excluded items
Ran all docker tests, a few reference files were updated from the changes.
#988

Rework exclusion handling to publish metrics

---

tests/bazel/Makefile

Yesterday bazel was updated and broke our tests.
[no changelog]

Pin bazel version for test

---

pyproject.toml

pyproject.toml: Remove duplicated classifier

---

cspell.json
doc/source/faq.rst

See https://github.com/gcovr/gcovr/pull/1046#issuecomment-2585253400.
[no changelog]

Add FAQ entry for decision coverage

---

CHANGELOG.rst
src/gcovr/data_model/coverage.py
src/gcovr/decision_analysis.py
src/gcovr/formats/cobertura/read.py
src/gcovr/formats/gcov/parser/common.py
src/gcovr/formats/gcov/parser/json.py
src/gcovr/formats/gcov/parser/text.py
src/gcovr/formats/html/write.py
tests/html-file-not-found/reference/clang-10/coverage.does-not-exist.cpp.1630668f5825154f66e6eb6df88396a9.html
tests/html-file-not-found/reference/gcc-5/coverage.does-not-exist.cpp.1630668f5825154f66e6eb6df88396a9.html
tests/test_gcov_parser.py

This PR adds back references into the data model to get the location information if a data error is raised. Also we are able to read in JSON data files without having access to the original sources to analyse user errors.

Improve debug of data errors

---

.github/workflows/CI.yml
cspell.json

Only check changed files for spell errors

---

src/gcovr/formats/gcov/read.py
tests/.gitignore
tests/exclude-throw-branches/Makefile
tests/test_gcovr.py
tests/worker-exception/Makefile
tests/worker-exception/gcov-stub
tests/worker-exception/main.cpp

Add test for a worker exception and add stdout of GCOV to the log message.
[no changelog]

Test worker exception handling

---

src/gcovr/formats/html/default/directory_page.content.html
src/gcovr/formats/html/default/directory_page.summary.html
src/gcovr/formats/html/default/functions_page.content.html
src/gcovr/formats/html/default/functions_page.summary.html
src/gcovr/formats/html/default/source_page.content.html
src/gcovr/formats/html/default/source_page.navigation.html
src/gcovr/formats/html/default/source_page.summary.html
src/gcovr/formats/html/github/directory_page.content.html
src/gcovr/formats/html/github/directory_page.summary.html
src/gcovr/formats/html/github/functions_page.content.html
src/gcovr/formats/html/github/functions_page.summary.html
src/gcovr/formats/html/github/source_page.content.html
src/gcovr/formats/html/github/source_page.navigation.html
src/gcovr/formats/html/github/source_page.summary.html
src/gcovr/formats/html/write.py

Replace EXCLUDE_CONDITION_COVERAGE with SHOW_CONDITION_COVERAGE. The old flag was as "No conditions available" and in the usage with "not EXCLUDE_CONDITION_COVERAGE".
[no changelog]

Remove double negation in flag

---

CHANGELOG.rst
src/gcovr/formats/__init__.py
src/gcovr/formats/sonarqube/__init__.py
src/gcovr/formats/sonarqube/write.py
tests/simple1/Makefile
tests/simple1/reference/clang-10/sonarqube.xml
tests/simple1/reference/gcc-5/sonarqube.xml

Add option to pretty print the sonarqube report.

Add option `--sonarqube-pretty`

---

CHANGELOG.rst
src/gcovr/configuration.py
src/gcovr/exclusions/__init__.py
src/gcovr/exclusions/markers.py
src/gcovr/exclusions/utils.py
src/gcovr/formats/gcov/__init__.py
tests/const-functions/Makefile
tests/different-branches/Makefile
tests/exclude-line/Makefile
tests/less-lines/Makefile

If a line is excluded by comment markers but has a count != 0 a warning is printed.
Closes #1125

Add optional warning if line has hits but is excluded
